---
title: "German Policy Agendas"
output: github_document
---


## General Information

All data available in this repo originally haven been coded following the [German specific codebook](https://github.com/benjaminguinaudeau/GPA/raw/master/codebook.pdf). The latest version is available on the [Comparative Agendas website](https://www.comparativeagendas.net). To ensure the international comparability, German specific categories have been converted into the categories from the master codebook of the Comparative Agenda Project. German specific codes are available on request. 

Human coders working on the German Policy Agendas are trained on previously coded data. The training data assembles documents of each class coded as part of the project; e.g. laws and bills, executive statements etc. The topics and documents included in the training data are of increasing difficulty. The coding of original data is done at least double-blind, most often triple-blind following the training. If there is no overlap between all coders then cases are discussed with a principle investigator. Instances that the coders and the principle investigator cannot agree on are referred to the whole project group, including the project director. If no consensus is reached among the whole project group then a vote on the coding takes place. 

These datasets have been published in the [Journal of Legislative Studies](https://www.tandfonline.com/doi/full/10.1080/13572334.2021.2010395). Do not forget to quote us if you use it (see quote example below).

## Data

Following datasets are available: 

+ [Most-Important Problems](https://github.com/benjaminguinaudeau/GPA/raw/master/data/mip-1976-2017_release_2.5.csv)
+ [Executive speeches](https://github.com/benjaminguinaudeau/GPA/raw/master/data/speeches_1976-2017_release_2.5.csv)
+ [Parliamentary questions](https://github.com/benjaminguinaudeau/GPA/raw/master/data/anfrage_1976-2017_release_2.5.csv)
+ [Private and public bills](https://github.com/benjaminguinaudeau/GPA/raw/master/data/bills_1976-2017_release_2.5.csv)
+ [Laws](https://github.com/benjaminguinaudeau/GPA/raw/master/data/laws_1976-2017_release_2.5.csv)
+ [Manifestos](https://github.com/benjaminguinaudeau/GPA/raw/master/data/manifesto_1949-2013_release_2.5.csv)



## How to cite? 

*For MIP, Speeches, parliamentary questions, bills and laws*

> Breunig, C., Guinaudeau, B., & Schnatterer, T. (2021). Policy agendas in Germany–database and descriptive insights. The Journal of Legislative Studies, 1-13.

*For Manifestos*

> Guinaudeau, I. (2015). Documentation on the coding of German manifestos. Working paper, Sciences Po Bordeaux



